/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFullLogo: typeof import('./src/components/AppFullLogo.vue')['default']
    AppLoader: typeof import('./src/components/AppLoader.vue')['default']
    BackgroundImage: typeof import('./src/components/welcome-page/parallax/components/images/BackgroundImage.vue')['default']
    BigCloudImage: typeof import('./src/components/welcome-page/parallax/components/images/BigCloudImage.vue')['default']
    BranchImage: typeof import('./src/components/welcome-page/parallax/components/images/BranchImage.vue')['default']
    BuildingImage: typeof import('./src/components/welcome-page/parallax/components/images/BuildingImage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    GuestLayout: typeof import('./src/components/layouts/GuestLayout.vue')['default']
    LogoImage: typeof import('./src/components/welcome-page/parallax/components/images/LogoImage.vue')['default']
    ParallaxCard: typeof import('./src/components/welcome-page/parallax/components/ParallaxCard.vue')['default']
    ParallaxCloseButton: typeof import('./src/components/welcome-page/parallax/components/ParallaxCloseButton.vue')['default']
    ParallaxComponent: typeof import('./src/components/welcome-page/parallax/ParallaxComponent.vue')['default']
    ParallaxContainer: typeof import('./src/components/welcome-page/parallax/components/ParallaxContainer.vue')['default']
    ParallaxExclamation: typeof import('./src/components/welcome-page/parallax/components/ParallaxExclamation.vue')['default']
    ParallaxItems: typeof import('./src/components/welcome-page/parallax/components/ParallaxItems.vue')['default']
    ParallaxLangChanger: typeof import('./src/components/welcome-page/parallax/components/ParallaxLangChanger.vue')['default']
    ParallaxProgress: typeof import('./src/components/welcome-page/parallax/components/ParallaxProgress.vue')['default']
    ParallaxScene: typeof import('./src/components/welcome-page/parallax/components/ParallaxScene.vue')['default']
    ParallaxSoundButton: typeof import('./src/components/welcome-page/parallax/components/ParallaxSoundButton.vue')['default']
    ParallaxSoundPlayer: typeof import('./src/components/welcome-page/parallax/components/ParallaxSoundPlayer.vue')['default']
    ParallaxWave: typeof import('./src/components/welcome-page/parallax/components/ParallaxWave.vue')['default']
    ParallaxWelcomeCard: typeof import('./src/components/welcome-page/parallax/components/ParallaxWelcomeCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmallCloud: typeof import('./src/components/welcome-page/parallax/components/images/SmallCloud.vue')['default']
    StatueImage: typeof import('./src/components/welcome-page/parallax/components/images/StatueImage.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
