version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    container_name: frontend_lib
    restart: unless-stopped
    user: ${UID}:${GID}
    volumes:
      - ./:/app
    ports:
      - "8080:5173"
