name: CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Installing Deps
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Type Cheking
        run: npm run type-check

      - name: Building
        run: npm run build


  UnitTest:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Installing Deps
        run: npm ci

      - name: Unit testing
        run: npm run test:unit

  E2ETest:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Installing Deps
        run: npm ci

      - name: E2E testing
        run: npm run test:e2e